name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linting:
    uses: ./.github/workflows/format-and-lint.yml

  testing:
    uses: ./.github/workflows/run-tests.yml

  building:
    needs: [linting, testing]
    uses: ./.github/workflows/build-docker.yml
