name: Reusable - Format and Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'

    # pipxの代わりにpipでpoetryをインストール
    - name: Install poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Run linter (Ruff)
      run: poetry run ruff check .

    - name: Check formatting (Black)
      run: poetry run black --check .
