name: Reusable - Format and Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # requirements.txtを使って依存関係をインストール
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run linter (Ruff)
      run: ruff check .

    - name: Check formatting (Black)
      run: black --check .
