name: Reusable - Run Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'

    - name: Install pipx
      run: pip install pipx

    - name: Install poetry using pipx
      run: pipx install poetry

    # pipxのパスをGITHUB_PATHに追加
    - name: Add pipx to PATH
      run: pipx ensurepath >> $GITHUB_PATH

    - name: Install dependencies
      run: poetry install

    - name: Run tests (Pytest)
      run: poetry run pytest
